"""Shared solver limits for routing and backend execution."""

MEEP_MAX_SCAN_POINTS = 288
MEEP_HIGH_RESOLUTION = 60
MEEP_HIGH_RESOLUTION_SCAN_POINTS = 96
MEEP_MAX_ARRAY_PARTICLES = 25
MEEP_MAX_WORKERS = 2

RCWA_MAX_SCAN_POINTS = 96
RCWA_GRID_SIZE = 32
RCWA_HARMONICS = 3
GRCWA_NG = 25
